services:
  ros:
    network_mode: "host"
    privileged: true
    tty: true
    build:
      context: .
      args:
        ROS_DISTRO: rolling-ros-base-noble
        USERNAME: ros
        WORKSPACE_PATH: /home/ros/ros_ws
        ROSDEP_SOURCE: file:///home/ros/ros_ws/rosdep/rosdep.yaml
        USER_UID: 1001
    image: ros2-ws-template
    container_name: ros2-ws-template
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./src:/home/ros/ros_ws/src
      - ./launch:/home/ros/ros_ws/launch
      - ./config:/home/ros/ros_ws/config
      - ./rosdep:/home/ros/ros_ws/rosdep
    command: ["bash", "-c", "source install/setup.bash && ros2 launch launch/ros.launch.py"]
