services:
  ros:
    network_mode: "host"
    privileged: true
    tty: true
    build:
      context: .
      args:
        ROS_DISTRO: rolling-ros-base-noble
        USERNAME: ros
        USER_UID: 1001
        PROJECT_PATH: /home/ros
        LAUNCH_FILE: ros.launch.py
    image: ros2-ws-template
    container_name: ros2-ws-template
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./src:/home/ros/src
      - ./launch:/home/ros/launch
      - ./config:/home/ros/config
      - ./rosdep:/home/ros/rosdep
    command: ["bash", "-c", "source install/setup.bash && ros2 launch launch/ros.launch.py"]
